version: "3.9"
name: dapp

services:
  db:
    container_name: db
    image: postgres
    restart: always
#    build:
#      dockerfile: db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d/
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/
    ports:
      - "${DB_PORT}:${DB_PORT}"

  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db

  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CLIENT_DEV_PORT=${CLIENT_DEV_PORT}
      - CLIENT_PROD_PORT=${CLIENT_PROD_PORT}
    ports:
      - "${CLIENT_PROD_PORT}:${CLIENT_PROD_PORT}"
    depends_on:
      - api
